default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: bus_admin_development

test:
  <<: *default
  database: bus_admin_test

production:
  <<: *default
  database: bus_admin_production
  username: bus_admin
  password: <%= ENV['BUS_ADMIN_DATABASE_PASSWORD'] %>
